title: Holden Daugherty
author: hdaugherty
email: holdendaugherty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Holdendaugherty.com is a website built to document my journeys through
  open source and becoming a better developer. I will use a blog to tell 
  my story and will also include any projects I work on along the way in my 
  portfolio. 

# social links
twitter_username: @daughertyh90
github_username:  @hdaugherty

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
